language: dart
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache
before_script: npm install

jobs:
  include:
    - dart: 2.4.0
      name: "SDK: 2.4.0"
      script:
        - dartanalyzer .
        - pub run test -P all -P travis
    - dart: stable
      name: "SDK: stable"
      script:
        - dartanalyzer .
        - pub run test -P all -P travis
    - dart: dev
      name: "SDK: dev"
      script:
        - dartanalyzer .
        - pub run test -P all -P travis
