language: dart

dart:
  - 1.24.3
  - 2.0.0

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

before_script: npm install
script:
  - dartanalyzer .
  - ./tool/travis.sh test
