language: dart

dart:
  - 1.24.3
  - stable

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

before_install:
  - ./pub2get.sh
before_script: npm install
script:
  - dartanalyzer .
  - ./tool/travis.sh test
